// Copies the compiled LettuceMarket ABI + bytecode to the frontend.
// Run after: npx hardhat compile
// Called automatically by: npm run build:contracts

const fs   = require("fs");
const path = require("path");

const ARTIFACT_PATH = path.join(
  __dirname, "..", "artifacts", "contracts",
  "Lettuce_contract.sol", "LettuceMarket.json"
);

const OUTPUT_PATH = path.join(
  __dirname, "..", "frontend", "src", "contractArtifact.js"
);

if (!fs.existsSync(ARTIFACT_PATH)) {
  console.error("❌  Artifact not found:", ARTIFACT_PATH);
  console.error("   Run: npx hardhat compile");
  process.exit(1);
}

const artifact = JSON.parse(fs.readFileSync(ARTIFACT_PATH, "utf8"));
const { abi, bytecode } = artifact;

if (!bytecode || bytecode === "0x") {
  console.error("❌  Bytecode is empty — did compilation succeed?");
  process.exit(1);
}

// Verify the ABI contains the constructor so ContractFactory works
const hasConstructor = abi.some((entry) => entry.type === "constructor");
if (!hasConstructor) {
  console.warn("⚠️   ABI has no constructor entry — ContractFactory may fail");
}

const output = `// Auto-generated by npm run build:contracts — do not edit manually.
// Regenerate with: npm run build:contracts  (from the project root)
// The ABI here is the full JSON ABI from Hardhat, which includes the
// constructor entry required by ethers ContractFactory.

export const LETTUCE_MARKET_ABI = ${JSON.stringify(abi, null, 2)};

export const LETTUCE_MARKET_BYTECODE = "${bytecode}";
`;

fs.writeFileSync(OUTPUT_PATH, output, "utf8");
console.log("✅  LettuceMarket ABI + bytecode copied to frontend/src/contractArtifact.js");
console.log("   Constructor found in ABI:", hasConstructor);
console.log("   Bytecode size:", Math.round(bytecode.length / 2 - 1), "bytes");
